title:              Data Science random chapters
email:              milica.misk@gmail.com
description:        Statistics roulette 
author:             Milica Miskovic
baseurl:            
url:                "https://milicamisk.github.io/"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    MilicaMisk
#facebook_username:  StartBootstrap
instagram_username:  
linkedin_username: Milica Miskovic

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
